name: scoreboardpluginah
version: 1.0.0
main: de.echosmp.echosmp.EchoSmpPlugin
api-version: '1.21'
author: EchoSMP
description: Sidebar-Scoreboard für Echo SMP
commands:
  scoreboard:
    description: Öffnet die EchoSMP-Scoreboard-Einstellungen
    usage: /scoreboard settings
    aliases:
      - scoreboardsettings
  sell:
    description: Öffnet das EchoSMP-Verkaufsmenü
    usage: /sell
  ah:
    description: Öffnet das EchoSMP-Auktionshaus
    usage: /ah
    aliases:
      - auctionhouse
